/****** Object:  Table [dbo].[CRC_ANALYSIS_JOB]    Script Date: 1/21/2022 10:40:51 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CRC_ANALYSIS_JOB](
	[job_id] [varchar](10) NOT NULL,
	[queue_name] [varchar](50) NULL,
	[status_type_id] [int] NULL,
	[domain_id] [varchar](255) NULL,
	[project_id] [varchar](500) NULL,
	[user_id] [varchar](255) NULL,
	[request_xml] [varchar](max) NULL,
	[create_date] [datetime] NULL,
	[update_date] [datetime] NULL,
 CONSTRAINT [ANALSIS_JOB_PK] PRIMARY KEY CLUSTERED 
(
	[job_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CRC_DB_LOOKUP]    Script Date: 1/21/2022 10:40:51 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CRC_DB_LOOKUP](
	[C_DOMAIN_ID] [varchar](255) NOT NULL,
	[C_PROJECT_PATH] [varchar](255) NOT NULL,
	[C_OWNER_ID] [varchar](255) NOT NULL,
	[C_DB_FULLSCHEMA] [varchar](255) NOT NULL,
	[C_DB_DATASOURCE] [varchar](255) NOT NULL,
	[C_DB_SERVERTYPE] [varchar](255) NOT NULL,
	[C_DB_NICENAME] [varchar](255) NULL,
	[C_DB_TOOLTIP] [varchar](255) NULL,
	[C_COMMENT] [varchar](max) NULL,
	[C_ENTRY_DATE] [datetime] NULL,
	[C_CHANGE_DATE] [datetime] NULL,
	[C_STATUS_CD] [char](1) NULL,
 CONSTRAINT [CRC_DB_LOOKUP_PK] PRIMARY KEY CLUSTERED 
(
	[C_DOMAIN_ID] ASC,
	[C_PROJECT_PATH] ASC,
	[C_OWNER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HIVE_CELL_PARAMS]    Script Date: 1/21/2022 10:40:51 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HIVE_CELL_PARAMS](
	[ID] [int] NOT NULL,
	[DATATYPE_CD] [varchar](50) NULL,
	[CELL_ID] [varchar](50) NOT NULL,
	[PARAM_NAME_CD] [varchar](200) NOT NULL,
	[VALUE] [varchar](max) NULL,
	[CHANGE_DATE] [datetime] NULL,
	[ENTRY_DATE] [datetime] NULL,
	[CHANGEBY_CHAR] [varchar](50) NULL,
	[STATUS_CD] [varchar](50) NULL,
 CONSTRAINT [HIVE_CE__PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[IM_DB_LOOKUP]    Script Date: 1/21/2022 10:40:51 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IM_DB_LOOKUP](
	[C_DOMAIN_ID] [varchar](255) NOT NULL,
	[C_PROJECT_PATH] [varchar](255) NOT NULL,
	[C_OWNER_ID] [varchar](255) NOT NULL,
	[C_DB_FULLSCHEMA] [varchar](255) NOT NULL,
	[C_DB_DATASOURCE] [varchar](255) NOT NULL,
	[C_DB_SERVERTYPE] [varchar](255) NOT NULL,
	[C_DB_NICENAME] [varchar](255) NULL,
	[C_DB_TOOLTIP] [varchar](255) NULL,
	[C_COMMENT] [varchar](max) NULL,
	[C_ENTRY_DATE] [datetime] NULL,
	[C_CHANGE_DATE] [datetime] NULL,
	[C_STATUS_CD] [char](1) NULL,
 CONSTRAINT [IM_DB_LOOKUP_PK] PRIMARY KEY CLUSTERED 
(
	[C_DOMAIN_ID] ASC,
	[C_PROJECT_PATH] ASC,
	[C_OWNER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ONT_DB_LOOKUP]    Script Date: 1/21/2022 10:40:51 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ONT_DB_LOOKUP](
	[C_DOMAIN_ID] [varchar](255) NOT NULL,
	[C_PROJECT_PATH] [varchar](255) NOT NULL,
	[C_OWNER_ID] [varchar](255) NOT NULL,
	[C_DB_FULLSCHEMA] [varchar](255) NOT NULL,
	[C_DB_DATASOURCE] [varchar](255) NOT NULL,
	[C_DB_SERVERTYPE] [varchar](255) NOT NULL,
	[C_DB_NICENAME] [varchar](255) NULL,
	[C_DB_TOOLTIP] [varchar](255) NULL,
	[C_COMMENT] [varchar](max) NULL,
	[C_ENTRY_DATE] [datetime] NULL,
	[C_CHANGE_DATE] [datetime] NULL,
	[C_STATUS_CD] [char](1) NULL,
 CONSTRAINT [ONT_DB_LOOKUP_PK] PRIMARY KEY CLUSTERED 
(
	[C_DOMAIN_ID] ASC,
	[C_PROJECT_PATH] ASC,
	[C_OWNER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[WORK_DB_LOOKUP]    Script Date: 1/21/2022 10:40:51 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WORK_DB_LOOKUP](
	[C_DOMAIN_ID] [varchar](255) NOT NULL,
	[C_PROJECT_PATH] [varchar](255) NOT NULL,
	[C_OWNER_ID] [varchar](255) NOT NULL,
	[C_DB_FULLSCHEMA] [varchar](255) NOT NULL,
	[C_DB_DATASOURCE] [varchar](255) NOT NULL,
	[C_DB_SERVERTYPE] [varchar](255) NOT NULL,
	[C_DB_NICENAME] [varchar](255) NULL,
	[C_DB_TOOLTIP] [varchar](255) NULL,
	[C_COMMENT] [varchar](max) NULL,
	[C_ENTRY_DATE] [datetime] NULL,
	[C_CHANGE_DATE] [datetime] NULL,
	[C_STATUS_CD] [char](1) NULL,
 CONSTRAINT [WORK_DB_LOOKUP_PK] PRIMARY KEY CLUSTERED 
(
	[C_DOMAIN_ID] ASC,
	[C_PROJECT_PATH] ASC,
	[C_OWNER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
INSERT [dbo].[CRC_DB_LOOKUP] ([C_DOMAIN_ID], [C_PROJECT_PATH], [C_OWNER_ID], [C_DB_FULLSCHEMA], [C_DB_DATASOURCE], [C_DB_SERVERTYPE], [C_DB_NICENAME], [C_DB_TOOLTIP], [C_COMMENT], [C_ENTRY_DATE], [C_CHANGE_DATE], [C_STATUS_CD]) VALUES (N'i2b2demo', N'/ACT/', N'@', N'{DATABASE_NAME}.dbo', N'java:/QueryToolDemoDS', N'SQLSERVER', N'Demo', NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[CRC_DB_LOOKUP] ([C_DOMAIN_ID], [C_PROJECT_PATH], [C_OWNER_ID], [C_DB_FULLSCHEMA], [C_DB_DATASOURCE], [C_DB_SERVERTYPE], [C_DB_NICENAME], [C_DB_TOOLTIP], [C_COMMENT], [C_ENTRY_DATE], [C_CHANGE_DATE], [C_STATUS_CD]) VALUES (N'i2b2demo', N'/Demo/', N'@', N'{DATABASE_NAME}.dbo', N'java:/QueryToolDemoDS', N'SQLSERVER', N'Demo', NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (1, N'T', N'CRC', N'edu.harvard.i2b2.crc.delegate.ontology.operation.getterminfo', N'/getTermInfo', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (2, N'T', N'CRC', N'edu.harvard.i2b2.crc.delegate.ontology.operation.getchildren', N'/getChildren', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (3, N'T', N'CRC', N'edu.harvard.i2b2.crc.delegate.ontology.operation.getmodifierinfo', N'/getModifierInfo', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (4, N'T', N'CRC', N'queryprocessor.multifacttable', N'false', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (5, N'T', N'CRC', N'edu.harvard.i2b2.crc.pdo.paging.observation.size', N'7500', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (6, N'T', N'CRC', N'edu.harvard.i2b2.crc.pdo.paging.iteration', N'100', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (7, N'T', N'CRC', N'edu.harvard.i2b2.crc.pdo.paging.inputlist.minpercent', N'20', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (8, N'T', N'CRC', N'edu.harvard.i2b2.crc.pdo.paging.inputlist.minsize', N'1', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (9, N'T', N'CRC', N'edu.harvard.i2b2.crc.pdo.paging.method', N'SUBDIVIDE_INPUT_METHOD ', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (10, N'T', N'CRC', N'edu.harvard.i2b2.crc.pdo.request.timeoutmills', N'600000', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (11, N'T', N'CRC', N'edu.harvard.i2b2.crc.analysis.queue.medium.timeoutmills', N'3000', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (12, N'T', N'CRC', N'edu.harvard.i2b2.crc.analysis.queue.medium.maxjobcount', N'4', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (13, N'T', N'CRC', N'edu.harvard.i2b2.crc.analysis.queue.large.timeoutmills', N'43200000', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (14, N'T', N'CRC', N'edu.harvard.i2b2.crc.analysis.queue.large.maxjobcount', N'1', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (15, N'T', N'CRC', N'edu.harvard.i2b2.crc.analysis.queue.medium.jobcheck.timemills', N'60000', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (16, N'T', N'CRC', N'edu.harvard.i2b2.crc.analysis.queue.large.jobcheck.timemills', N'60000', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (17, N'T', N'CRC', N'edu.harvard.i2b2.crc.jms.small.timeoutsec', N'180', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (18, N'T', N'CRC', N'edu.harvard.i2b2.crc.jms.medium.timeoutsec', N'14400', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (19, N'T', N'CRC', N'edu.harvard.i2b2.crc.jms.large.timeoutsec', N'43200', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (20, N'T', N'CRC', N'edu.harvard.i2b2.crc.pm.serviceaccount.user', N'AGG_SERVICE_ACCOUNT', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (21, N'T', N'CRC', N'edu.harvard.i2b2.crc.pm.serviceaccount.password', N'demouser', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (22, N'T', N'CRC', N'edu.harvard.i2b2.crc.lockout.setfinderquery.count', N'7', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (23, N'T', N'CRC', N'edu.harvard.i2b2.crc.lockout.setfinderquery.day', N'30', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (24, N'T', N'CRC', N'edu.harvard.i2b2.crc.lockout.setfinderquery.zero.count', N'-1', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (25, N'T', N'CRC', N'edu.harvard.i2b2.crc.setfinderquery.obfuscation.count.sigma', N'1.323', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (26, N'T', N'CRC', N'edu.harvard.i2b2.crc.setfinderquery.obfuscation.breakdowncount.sigma', N'1.6', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (27, N'T', N'CRC', N'edu.harvard.i2b2.crc.setfinderquery.obfuscation.minimum.value', N'3', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (28, N'T', N'CRC', N'edu.harvard.i2b2.crc.i2b2SocketServer', N'7070', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (29, N'T', N'CRC', N'edu.harvard.i2b2.crc.setfinderquery.skiptemptable.maxconcept', N'40', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (30, N'T', N'CRC', N'queryprocessor.jndi.queryexecutormdblocal', N'ejb.querytool.QueryExecutorMDBLocal', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (31, N'T', N'CRC', N'queryprocessor.jndi.querymanagerlocal', N'ejb.querytool.QueryManagerLocal', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (32, N'T', N'CRC', N'queryprocessor.jndi.querymasterlocal', N'ejb.querytool.QueryMasterLocal', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (33, N'T', N'CRC', N'queryprocessor.jndi.queryinfolocal', N'ejb.querytool.QueryInfoLocal', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (34, N'T', N'CRC', N'queryprocessor.jndi.queryrunlocal', N'ejb.querytool.QueryRunLocal', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (35, N'T', N'CRC', N'queryprocessor.jndi.queryresultlocal', N'ejb.querytool.QueryResultLocal', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (36, N'T', N'CRC', N'queryprocessor.jndi.pdoquerylocal', N'ejb.querytool.PdoQueryLocal', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (37, N'T', N'CRC', N'queryprocessor.jndi.querymanagerremote', N'ejb.querytool.QueryManager', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (38, N'T', N'CRC', N'queryprocessor.jndi.queryexecutormdbremote', N'ejb.querytool.QueryExecutorMDB', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (39, N'T', N'CRC', N'queryprocessor.jndi.queue.connectionfactory', N'ConnectionFactory', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (40, N'T', N'CRC', N'queryprocessor.jndi.queue.response_queue', N'queue/jms.querytool.QueryResponse', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (41, N'T', N'CRC', N'queryprocessor.jndi.queue.executor_queue', N'queue/jms.querytool.QueryExecutor', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (42, N'T', N'CRC', N'I2B2_MESSAGE_ERROR_AUTHENTICATION_FAILURE', N'Authentication failure.', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (43, N'T', N'CRC', N'I2B2_MESSAGE_ERROR_INVALID_MESSAGE', N'Invalid message body', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (44, N'T', N'CRC', N'I2B2_MESSAGE_STATUS_QUEUED', N'QUEUED', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (45, N'T', N'CRC', N'I2B2_MESSAGE_STATUS_PROCESSING', N'PROCESSING', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (46, N'T', N'CRC', N'I2B2_MESSAGE_STATUS_ERROR', N'ERROR', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (47, N'T', N'CRC', N'I2B2_MESSAGE_STATUS_FINISHED', N'FINISHED', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (48, N'T', N'CRC', N'I2B2_MESSAGE_STATUS_COMPLETED', N'COMPLETED', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (49, N'T', N'CRC', N'I2B2_MESSAGE_STATUS_INCOMPLE', N'INCOMPLETE', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (50, N'U', N'CRC', N'queryprocessor.ws.ontology.url', N'/services/OntologyService/getTermInfo', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (51, N'U', N'CRC', N'queryprocessor.ws.pm.url', N'/services/PMService/getServices', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (52, N'U', N'WORK', N'workplace.ws.pm.url', N'/services/PMService/getServices', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (53, N'U', N'ONT', N'ontology.ws.pm.url', N'/services/PMService/getServices', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (54, N'U', N'ONT', N'edu.harvard.i2b2.ontology.ws.crc.url', N'/services/QueryToolService', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (55, N'U', N'ONT', N'edu.harvard.i2b2.ontology.ws.fr.url', N'/services/FRService/', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (56, N'T', N'ONT', N'edu.harvard.i2b2.ontology.ws.fr.tempspace', N'/tmp', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (57, N'T', N'ONT', N'edu.harvard.i2b2.ontology.ws.fr.timeout', N'10000', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (58, N'T', N'ONT', N'edu.harvard.i2b2.ontology.ws.fr.filethreshold', N'4000', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (59, N'T', N'ONT', N'edu.harvard.i2b2.ontology.ws.fr.attachmentname', N'cid', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (60, N'T', N'ONT', N'edu.harvard.i2b2.ontology.ws.fr.operation', N'urn:recvfileRequest', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (61, N'T', N'ONT', N'applicationName', N'Ontology Cell', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (62, N'T', N'ONT', N'applicationVersion', N'1.7', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (63, N'T', N'CRC', N'applicationName', N'CRC Cell', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (64, N'T', N'CRC', N'applicationVersion', N'1.7', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (65, N'T', N'ONT', N'ontology.terminal.delimiter', N'true', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (66, N'T', N'CRC', N'edu.harvard.i2b2.crc.setfinder.querygenerator.version', N'1.7', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (67, N'U', N'CRC', N'edu.harvard.i2b2.crc.delegate.ontology.url', N'/services/OntologyService', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (68, N'U', N'IM', N'im.ws.pm.url', N'/services/PMService/getServices', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (69, N'T', N'IM', N'im.checkPatientInProject', N'true', NULL, NULL, NULL, N'A')
INSERT [dbo].[HIVE_CELL_PARAMS] ([ID], [DATATYPE_CD], [CELL_ID], [PARAM_NAME_CD], [VALUE], [CHANGE_DATE], [ENTRY_DATE], [CHANGEBY_CHAR], [STATUS_CD]) VALUES (70, N'T', N'IM', N'im.empi.service', N'none', NULL, NULL, NULL, N'A')
GO
INSERT [dbo].[IM_DB_LOOKUP] ([C_DOMAIN_ID], [C_PROJECT_PATH], [C_OWNER_ID], [C_DB_FULLSCHEMA], [C_DB_DATASOURCE], [C_DB_SERVERTYPE], [C_DB_NICENAME], [C_DB_TOOLTIP], [C_COMMENT], [C_ENTRY_DATE], [C_CHANGE_DATE], [C_STATUS_CD]) VALUES (N'i2b2demo', N'Demo/', N'@', N'{DATABASE_NAME}.dbo', N'java:/IMDemoDS', N'SQLSERVER', N'IM', NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[ONT_DB_LOOKUP] ([C_DOMAIN_ID], [C_PROJECT_PATH], [C_OWNER_ID], [C_DB_FULLSCHEMA], [C_DB_DATASOURCE], [C_DB_SERVERTYPE], [C_DB_NICENAME], [C_DB_TOOLTIP], [C_COMMENT], [C_ENTRY_DATE], [C_CHANGE_DATE], [C_STATUS_CD]) VALUES (N'i2b2demo', N'ACT/', N'@', N'{DATABASE_NAME}.dbo', N'java:/OntologyACTDS', N'SQLSERVER', N'Metadata', NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ONT_DB_LOOKUP] ([C_DOMAIN_ID], [C_PROJECT_PATH], [C_OWNER_ID], [C_DB_FULLSCHEMA], [C_DB_DATASOURCE], [C_DB_SERVERTYPE], [C_DB_NICENAME], [C_DB_TOOLTIP], [C_COMMENT], [C_ENTRY_DATE], [C_CHANGE_DATE], [C_STATUS_CD]) VALUES (N'i2b2demo', N'Demo/', N'@', N'{DATABASE_NAME}.dbo', N'java:/OntologyDemoDS', N'SQLSERVER', N'Metadata', NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[WORK_DB_LOOKUP] ([C_DOMAIN_ID], [C_PROJECT_PATH], [C_OWNER_ID], [C_DB_FULLSCHEMA], [C_DB_DATASOURCE], [C_DB_SERVERTYPE], [C_DB_NICENAME], [C_DB_TOOLTIP], [C_COMMENT], [C_ENTRY_DATE], [C_CHANGE_DATE], [C_STATUS_CD]) VALUES (N'i2b2demo', N'ACT/', N'@', N'{DATABASE_NAME}.dbo', N'java:/WorkplaceDemoDS', N'SQLSERVER', N'Workplace', NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[WORK_DB_LOOKUP] ([C_DOMAIN_ID], [C_PROJECT_PATH], [C_OWNER_ID], [C_DB_FULLSCHEMA], [C_DB_DATASOURCE], [C_DB_SERVERTYPE], [C_DB_NICENAME], [C_DB_TOOLTIP], [C_COMMENT], [C_ENTRY_DATE], [C_CHANGE_DATE], [C_STATUS_CD]) VALUES (N'i2b2demo', N'Demo/', N'@', N'{DATABASE_NAME}.dbo', N'java:/WorkplaceDemoDS', N'SQLSERVER', N'Workplace', NULL, NULL, NULL, NULL, NULL)
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [CRC_IDX_AJ_QNSTID]    Script Date: 1/21/2022 10:40:52 AM ******/
CREATE NONCLUSTERED INDEX [CRC_IDX_AJ_QNSTID] ON [dbo].[CRC_ANALYSIS_JOB]
(
	[queue_name] ASC,
	[status_type_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

